services:
  dashboard:
    build: .
    image: eka-dashboard:latest
    container_name: eka_dashboard
    restart: unless-stopped
    # Use standard bridge mode with port mapping to enforce Port 80
    ports:
      - "80:5000"
    pid: host # Essential for Process List
    privileged: true # Essential for low-level hardware access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker Management
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket # Systemd Control
      - /proc:/host/proc:ro # Hardware Stats
      - /sys:/host/sys:ro # Hardware Stats
      - /:/host/root # File Manager Access
      - /etc/wireguard:/etc/wireguard # Manage WireGuard Config
      - ./data:/app/data # Persist configs/license
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ROOT=/host/root
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
